# Generated by Django 3.1.3 on 2020-12-14 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('trans', models.CharField(max_length=150)),
                ('user_id', models.IntegerField()),
                ('source_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_from', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
